"""Build the paper figures from the archived runs. The particle state for Figure 1 is generated by the same stepper the paper describes and stored in fig1_state.npz."""

import json, sys
from pathlib import Path
import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

HERE = Path(__file__).resolve().parent
FIG = HERE.parent / "figures"
CODE = HERE.parents[1]
ARCH = CODE / "output"
REVIEW = HERE.parent / "evidence"
sys.path.insert(0, str(CODE))

plt.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans"],
        "font.size": 9,
        "axes.labelsize": 9,
        "axes.titlesize": 9,
        "legend.fontsize": 8,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "axes.linewidth": 0.7,
        "lines.linewidth": 1.1,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "grid.linewidth": 0.5,
        "figure.dpi": 160,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,
        "pdf.fonttype": 42,
    }
)
C = {
    "RAW": "#8c8c8c",
    "WITHIN": "#1f77b4",
    "FULL": "#c1272d",
    "SINGLE": "#555555",
    "RQMC": "#2e7d32",
    "ref": "#111111",
}
NAME = {
    "RAW": "reflected",
    "WITHIN": "within-sign",
    "FULL": "sign-switched",
    "SINGLE": "independent",
    "RQMC": "RQMC",
}


def jload(p):
    return json.load(open(p))


# ---------------------------------------------------------------- figure 1
def fig_construction():  # Figure 1 in the manuscript (Section 3.2)
    """A real paired state: the interleaved-sign configuration after 10 steps."""
    from studies.sign_structure_map import config
    from coupled_gradient_particles import advance_pair

    N, K, SEED = 12, 10, 2
    x0, m0, ul = config("clustered", N)
    captured = {}

    def capture(k, xA, mA, vA, xB, mB, vB):
        if k == K - 1:
            captured.update(xA=xA, mA=mA, xB=xB, mB=mB)

    advance_pair(
        (x0, m0, ul),
        0.1,
        0.005,
        K,
        np.random.default_rng(SEED),
        "FULL",
        lambda u: u,
        pre_diffusion=capture,
    )
    xA, mA, xB, mB = (captured[k] for k in ("xA", "mA", "xB", "mB"))
    assert np.all(np.diff(xA) >= 0) and np.all(np.diff(xB) >= 0)
    sA, sB = np.sign(mA), np.sign(mB)

    fig, axes = plt.subplots(1, 2, figsize=(4.8, 2.5))
    for ax, rule in zip(axes, ("rank", "within")):
        for y, xx, ss in ((1.0, xA, sA), (0.0, xB, sB)):
            for xi, si in zip(xx, ss):
                ax.plot(
                    [xi],
                    [y],
                    marker="o" if si > 0 else "s",
                    ms=5.4,
                    mfc="#e8e8e8" if si > 0 else "#333333",
                    mec="#111111",
                    mew=0.6,
                    linestyle="none",
                    zorder=3,
                )
        if rule == "rank":
            pairs = [(i, i, sA[i] * sB[i]) for i in range(len(xA))]
            ttl = "rank matching\nmultiplier $-\\,\\mathrm{sgn}(m^A_i)\\,\\mathrm{sgn}(m^B_i)$"
        else:
            pairs = []
            for sgn in (1.0, -1.0):
                ia = np.flatnonzero(sA == sgn)
                ib = np.flatnonzero(sB == sgn)
                q = min(len(ia), len(ib))
                pairs += [(ia[k], ib[k], 1.0) for k in range(q)]
            ttl = "within-sign matching\nmultiplier $-1$"
        for i, j, mult in pairs:
            sync = mult < 0
            ax.plot(
                [xA[i], xB[j]],
                [1.0, 0.0],
                color="#c1272d" if sync else "#4d4d4d",
                ls=(0, (2.4, 1.4)) if sync else "-",
                lw=1.0,
                zorder=2,
                alpha=0.95,
            )
        ax.set_ylim(-0.55, 1.55)
        ax.set_yticks([0.0, 1.0])
        ax.set_yticklabels(["simulation $B$", "simulation $A$"])
        ax.set_xlabel("position $x$")
        ax.set_xlim(min(xA.min(), xB.min()) - 0.04, max(xA.max(), xB.max()) + 0.04)
        ax.grid(axis="x", alpha=0.2)
        ax.grid(axis="y", alpha=0)
        ax.set_axisbelow(True)

    h = [
        Line2D(
            [],
            [],
            marker="o",
            ls="none",
            mfc="#e8e8e8",
            mec="#111",
            ms=5.4,
            label="$m_i>0$",
        ),
        Line2D(
            [],
            [],
            marker="s",
            ls="none",
            mfc="#333333",
            mec="#111",
            ms=5.4,
            label="$m_i<0$",
        ),
        Line2D([], [], color="#4d4d4d", lw=1.0, label="reflected pair: $Z^B_i=-Z^A_i$"),
        Line2D(
            [],
            [],
            color="#c1272d",
            lw=1.0,
            ls=(0, (2.4, 1.4)),
            label="synchronized pair: $Z^B_i=Z^A_i$",
        ),
    ]
    fig.legend(
        handles=h,
        ncol=2,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.17),
        frameon=False,
        columnspacing=1.5,
        handletextpad=0.6,
    )
    fig.tight_layout()
    fig.savefig(FIG / "fig1_construction.pdf")
    plt.close(fig)
    np.savez(
        HERE / "fig1_state.npz",
        xA=xA,
        mA=mA,
        xB=xB,
        mB=mB,
        config=np.array(["clustered"]),
        N=N,
        K=K,
        seed=SEED,
    )
    print("fig1_construction.pdf")


# ---------------------------------------------------------------- figure 3
def fig_fields():  # Figure 3 in the manuscript (Section 4.2)
    z = np.load(REVIEW / "principal_fields.npz")
    x = z["x"]
    ref = z["reference"]
    fig, axes = plt.subplots(
        3, 1, figsize=(4.8, 5.5)
    )
    r = 3
    lim = 0
    for a in ("RAW", "FULL"):
        lim = max(
            lim, np.abs(z[f"{a}_A"][r] - ref).max(), np.abs(z[f"{a}_B"][r] - ref).max()
        )
    lim *= 1.08
    for ax, a in zip(axes[:2], ("RAW", "FULL")):
        ax.axhline(0.0, color="#111111", lw=0.6, ls=":")
        ax.plot(x, z[f"{a}_A"][r] - ref, color=C[a], lw=0.7, alpha=0.42)
        ax.plot(x, z[f"{a}_B"][r] - ref, color=C[a], lw=0.7, alpha=0.42)
        ax.plot(x, 0.5 * (z[f"{a}_A"][r] + z[f"{a}_B"][r]) - ref, color=C[a], lw=1.3)
        ax.set_xlim(-3, 3)
        ax.set_ylim(-lim, lim)
        ax.set_xlabel("$x$")
    axes[0].set_ylabel("error, $U-u_{\\mathrm{ref}}$")
    axes[1].set_ylabel("error, $U-u_{\\mathrm{ref}}$")

    ax = axes[2]
    v = {a: 0.5 * (z[f"{a}_A"] + z[f"{a}_B"]) for a in ("RAW", "WITHIN", "FULL")}
    var = {a: v[a].var(0, ddof=1) for a in v}
    g = np.abs(np.gradient(ref, x[1] - x[0]))
    ax2 = ax.twinx()
    ax2.fill_between(x, 0, g / g.max(), color="#9ecae1", alpha=0.45, lw=0, zorder=0)
    ax2.set_ylim(0, 2.6)
    ax2.set_yticks([])
    ax2.grid(False)

    def smooth(y, w=13):
        k = np.ones(w) / w
        return np.convolve(np.pad(y, w // 2, mode="edge"), k, mode="valid")[: len(y)]

    for num, den, col, lab, ls in (
        ("FULL", "RAW", C["FULL"], "sign-switched / reflected", "-"),
        ("FULL", "WITHIN", C["WITHIN"], "sign-switched / within-sign", "--"),
    ):
        rr = np.divide(
            var[num],
            var[den],
            out=np.full_like(var[num], np.nan),
            where=var[den] > 1e-10 * var[den].max(),
        )
        ax.plot(x, rr, color=col, lw=0.5, alpha=0.3, ls=ls, zorder=2)
        ax.plot(x, smooth(rr), color=col, lw=1.4, ls=ls, zorder=3, label=lab)
    ax.axhline(1.0, color="#111111", lw=0.6, ls=":")
    ax.set_xlim(-3, 3)
    ax.set_ylim(0, 1.45)
    ax.set_zorder(ax2.get_zorder() + 1)
    ax.patch.set_visible(False)
    ax.set_xlabel("$x$")
    ax.set_ylabel("pointwise variance ratio")
    ax.legend(
        frameon=False,
        loc="upper center",
        bbox_to_anchor=(0.5, -0.32),
        ncol=2,
        fontsize=8,
    )
    fig.tight_layout()
    fig.savefig(FIG / "fig3_fields.pdf")
    plt.close(fig)
    print("fig3_fields.pdf")


# ---------------------------------------------------------------- figure 5
def fig_profiles():  # Figure 5 in the manuscript (Section 4.5)
    mech = jload(ARCH / "profile_time_flux_sweep/mechanism.json")["rows"]
    sep = jload(ARCH / "matched_pair_separation/separation.json")["rows"]
    profiles = ["P1 single bump", "P2 two-pulse", "P3 oscillatory"]
    lab = {
        "P1 single bump": "single bump (2 sign regions)",
        "P2 two-pulse": "two-pulse (3)",
        "P3 oscillatory": "oscillatory (13)",
    }
    col = {
        "P1 single bump": "#4d4d4d",
        "P2 two-pulse": "#1f77b4",
        "P3 oscillatory": "#c1272d",
    }
    mk = {"P1 single bump": "o", "P2 two-pulse": "s", "P3 oscillatory": "^"}
    T = [0.25, 1.0, 2.0]
    fig, axes = plt.subplots(1, 2, figsize=(4.8, 2.9), sharex=True)

    ax = axes[0]
    for p in profiles:
        rs = [r for r in mech if r["profile"] == p]
        y = [r["full_over_within"] for r in rs]
        lo = [r["full_over_within"] - r["ci"][0] for r in rs]
        hi = [r["ci"][1] - r["full_over_within"] for r in rs]
        ax.errorbar(
            T,
            y,
            yerr=[lo, hi],
            color=col[p],
            marker=mk[p],
            ms=4.2,
            lw=1.1,
            capsize=2.5,
            label=lab[p],
        )
    ax.axhline(1.0, color="#111111", lw=0.7, ls=":")
    ax.set_xlabel("observation time $T$")
    ax.set_ylabel("integrated variance ratio")
    ax.set_xticks(T)
    ax.set_ylim(0.5, 1.08)

    ax = axes[1]
    for p in profiles:
        rs = [r for r in sep if r["kind"] == "matched_state" and r["profile"] == p]
        y = [r["ratio"] for r in rs]
        e = [2 * r["se"] for r in rs]
        ax.errorbar(
            T, y, yerr=e, color=col[p], marker=mk[p], ms=4.2, lw=1.1, capsize=2.5
        )
    ax.axhline(1.0, color="#111111", lw=0.7, ls=":")
    ax.set_xlabel("observation time $T$")
    ax.set_ylabel("partner-distance ratio")
    ax.set_xticks(T)
    ax.set_ylim(0.5, 1.08)

    h = [
        Line2D([], [], color=col[p], marker=mk[p], ms=4.2, lw=1.1, label=lab[p])
        for p in profiles
    ]
    fig.tight_layout()
    fig.legend(
        handles=h,
        ncol=3,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.10),
        frameon=False,
        columnspacing=1.8,
    )
    fig.savefig(FIG / "fig5_profiles.pdf")
    plt.close(fig)
    print("fig5_profiles.pdf")



# ---------------------------------------------------------------- figure 2
def fig_problem():  # Figure 2 in the manuscript (Section 4.1)
    d = np.load(REVIEW / "principal_fields.npz")
    x, ref = d["x"], d["reference"]

    def u_two(y):
        return 0.8 * np.exp(-((y + 0.7) ** 2) / (2 * 0.5**2)) - 0.5 * np.exp(
            -((y - 0.4) ** 2) / (2 * 0.3**2)
        )

    def u_bump(y):
        return 0.8 * np.exp(-((y + 0.2) ** 2) / (2 * 0.45**2))

    def u_osc(y):
        return 0.45 * np.sin(3 * y) * np.exp(-(y**2) / (2 * 1.1**2))

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.9), sharey=True)
    ax = axes[0]
    ax.plot(x, u_two(x), color="#888888", lw=1.0, ls=":", label="initial profile $u_0$")
    ax.plot(x, ref, color="#bbbbbb", lw=3.0, label=r"reference $u_{\mathrm{ref}}$ at $T=1$")
    ax.plot(
        x,
        0.5 * (d["FULL_A"][0] + d["FULL_B"][0]),
        color=C["FULL"],
        lw=0.9,
        label=r"one sign-switched pair $\bar U$",
        zorder=3,
    )
    ax.set_xlim(-3, 3)
    ax.set_xlabel("$x$")
    ax.set_ylabel("$u$")
    ax.legend(frameon=False, fontsize=7, loc="upper center", bbox_to_anchor=(0.5, -0.22), ncol=2)

    ax = axes[1]
    xx = np.linspace(-5, 5, 2001)
    for f, col, lab in (
        (u_bump, "#4d4d4d", "single bump (2 sign regions)"),
        (u_two, "#1f77b4", "two-pulse (3)"),
        (u_osc, "#c1272d", "oscillatory (13)"),
    ):
        ax.plot(xx, f(xx), color=col, lw=1.1, label=lab)
    ax.set_xlim(-4, 4)
    ax.set_xlabel("$x$")
    ax.legend(frameon=False, fontsize=7, loc="upper center", bbox_to_anchor=(0.5, -0.22), ncol=2)
    fig.tight_layout()
    fig.savefig(FIG / "fig2_problems.pdf")
    plt.close(fig)
    print("fig2_problems.pdf")


# ---------------------------------------------------------------- figure 4
def fig_cost():  # Figure 4 in the manuscript (Section 4.3)
    """Left: integrated MSE against execution time at N=8192, h=0.005, from the
    48 Test 1 realizations (curves b^2 + V/R, points from disjoint blocks), with
    the Experiment I plans. Right: the equal-work model ratio of Section 4.3."""
    d = np.load(REVIEW / "principal_fields.npz")
    x, ref = d["x"], d["reference"]
    dx = float(x[1] - x[0])

    def sq(g):
        return dx * float(np.sum(g**2))

    cost = jload(HERE / "numbers.json")["cost"]
    c8 = cost["per_pair_seconds"]["8192"]
    runs = {"SINGLE": d["RAW_A"]}
    for a in ("RAW", "WITHIN", "FULL"):
        runs[a] = 0.5 * (d[a + "_A"] + d[a + "_B"])
    per = {
        "SINGLE": cost["single_8192_s"],
        "RAW": c8["RAW"],
        "WITHIN": c8["WITHIN"],
        "FULL": c8["FULL"],
    }
    V = {a: dx * float(np.sum(r.var(axis=0, ddof=1))) for a, r in runs.items()}
    n = runs["FULL"].shape[0]
    # One bias estimate for every method (Corollary 3.4), from the switched pairs.
    b2 = sq(runs["FULL"].mean(axis=0) - ref) - V["FULL"] / n
    plans = jload(HERE / "numbers.json")["heldout_A"]["arms"]

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 3.15))
    ax = axes[0]
    for a in ("SINGLE", "RAW", "WITHIN", "FULL"):
        R = np.geomspace(1, 400, 300)
        ax.plot(R * per[a], b2 + V[a] / R, color=C[a], lw=1.2, label=NAME[a])
        Rs = [r for r in (1, 2, 4, 8, 16) if n // r >= 3]
        emp = []
        for r in Rs:
            blocks = runs[a][: (n // r) * r].reshape(n // r, r, -1).mean(axis=1)
            emp.append(np.mean([sq(bk - ref) for bk in blocks]))
        ax.plot(
            np.array(Rs) * per[a],
            emp,
            ls="none",
            marker="o",
            ms=3.2,
            mfc="white",
            mec=C[a],
            mew=0.9,
        )
    for a in ("SINGLE", "RAW", "FULL", "RQMC"):
        ax.plot(
            [plans[a]["work_s"]],
            [plans[a]["attained"]],
            ls="none",
            marker="D",
            ms=5,
            color=C[a],
            mec="black",
            mew=0.5,
            zorder=5,
        )
    ax.axhline(7e-6, color="#555555", lw=0.8, ls="--")
    ax.axhline(b2, color="#999999", lw=0.6, ls=":")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("execution time (s)")
    ax.set_ylabel("integrated MSE")
    handles = [
        Line2D([], [], color=C[a], lw=1.2, label=NAME[a])
        for a in ("SINGLE", "RAW", "WITHIN", "FULL")
    ]
    handles += [
        Line2D([], [], ls="none", marker="o", ms=3.2, mfc="white", mec="#444444",
               label="block estimates"),
        Line2D([], [], ls="none", marker="D", ms=5, color="#bbbbbb", mec="black",
               mew=0.5, label="Experiment I plans"),
        Line2D([], [], ls="none", marker="D", ms=5, color=C["RQMC"], mec="black",
               mew=0.5, label="RQMC plan"),
    ]
    ax.legend(handles=handles, frameon=False, fontsize=7, loc="upper right")

    ax = axes[1]
    jc = jload(ARCH / "bias_crossover_cell/joint_cell.json")["rows"]
    for row, ls in zip(jc, ["-", "--", ":"]):
        b2c, Vf, Vr = row["b2_full"], row["V_full"], row["V_raw"]
        Cf, Cr = row["cost_full"], row["cost_raw"]
        W = np.geomspace(max(Cf, Cr), 4000 * Cf, 500)
        ax.plot(
            W,
            (b2c + Vf * Cf / W) / (b2c + Vr * Cr / W),
            ls=ls,
            color=C["FULL"],
            lw=1.2,
            label=rf"$N={row['N']}$, $h={row['h']}$",
        )
        Bs = row["Bstar_full"]
        ax.plot(
            [Bs * Cf],
            [(b2c + Vf / Bs) / (b2c + Vr * Cr / (Bs * Cf))],
            marker="o",
            ms=4.5,
            mfc="white",
            mec=C["FULL"],
            mew=1.1,
            zorder=4,
        )
    ax.set_xscale("log")
    ax.set_xlabel("common work budget (s)")
    ax.set_ylabel("model MSE ratio")
    ax.axhline(1.0, color="#999999", lw=0.6)
    ax.set_ylim(0, 1.08)
    ax.legend(frameon=False, fontsize=7, loc="lower right")
    fig.tight_layout()
    fig.savefig(FIG / "fig4_cost.pdf")
    plt.close(fig)
    print("fig4_cost.pdf")


# ---------------------------------------------------------------- figure 6
def fig_controls():  # Figure 6 in the manuscript (Section 4.6, values in Table 7)
    rows = {
        (r["flux"], r["arm"]): r for r in jload(HERE / "numbers.json")["controls"]["rows"]
    }
    order = [
        ("RAW", "reflected"),
        ("RAW+RB", "+ conditional evaluation"),
        ("RAW+CVH(c*)", "+ heat control"),
        ("RAW+CVF(c*)", "+ velocity control"),
        ("WITHIN", "within-sign"),
        ("FULL", "sign-switched"),
        ("FULL+RB", "+ conditional evaluation"),
        ("FULL+CVH(c*)", "+ heat control"),
        ("FULL+CVF(c*)", "+ velocity control"),
    ]

    def col(a):
        if a.startswith("FULL"):
            return C["FULL"]
        return C["WITHIN"] if a == "WITHIN" else C["RAW"]

    fig, axes = plt.subplots(1, 2, figsize=(7.0, 3.0), sharey=True)
    for ax, flux in zip(axes, ("burgers", "cubic")):
        for i, (a, _) in enumerate(order):
            r = rows[(flux, a)]
            y = len(order) - 1 - i
            lo, hi = r["ci_vs_RAW"]
            v = r["ratio_vs_RAW"]
            ax.errorbar(
                [v],
                [y],
                xerr=[[v - lo], [hi - v]],
                fmt="o",
                ms=4,
                color=col(a),
                ecolor=col(a),
                elinewidth=0.9,
                capsize=2,
            )
            ax.plot(
                [r["var_times_cost_vs_RAW"]],
                [y],
                ls="none",
                marker="D",
                ms=4,
                mfc="white",
                mec=col(a),
                mew=0.9,
            )
        ax.axvline(1.0, color="#999999", lw=0.6)
        for y_sep in (3.5, 4.5):  # separate the reflected, within-sign and switched groups
            ax.axhline(y_sep, color="#cccccc", lw=0.6)
        ax.set_xscale("log")
        ax.set_xlim(0.05, 2.2)
        ax.set_xlabel("ratio to reflected pairing")
        ax.grid(axis="y", alpha=0)
    axes[0].set_yticks(range(len(order)))
    axes[0].set_yticklabels([lab for _, lab in order][::-1])
    handles = [
        Line2D([], [], ls="none", marker="o", ms=4, color="#444444",
               label="integrated variance (95% interval)"),
        Line2D([], [], ls="none", marker="D", ms=4, mfc="white", mec="#444444",
               label="variance times cost"),
    ]
    fig.legend(handles=handles, frameon=False, fontsize=7.5, loc="lower center",
               ncol=2, bbox_to_anchor=(0.6, -0.04))
    fig.tight_layout(rect=(0, 0.06, 1, 1))
    fig.savefig(FIG / "fig6_controls.pdf")
    plt.close(fig)
    print("fig6_controls.pdf")


if __name__ == "__main__":
    FIG.mkdir(exist_ok=True)
    fig_construction()
    fig_problem()
    fig_fields()
    fig_cost()
    fig_profiles()
    fig_controls()
