"""Build the manuscript figures from archived evidence.

Every panel names its archive in the caption; nothing is schematic except
Figure 1, whose particle state is generated by the same stepper the paper
describes (recorded in the output so it can be regenerated).
"""

import json, sys
from pathlib import Path
import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

HERE = Path(__file__).resolve().parent
FIG = HERE.parent / "figures"
CODE = HERE.parents[1]
ARCH = CODE / "output"
REVIEW = HERE.parent / "evidence"
sys.path.insert(0, str(CODE))

plt.rcParams.update(
    {
        "font.family": "serif",
        "font.serif": ["DejaVu Serif"],
        "font.size": 9,
        "axes.labelsize": 9,
        "axes.titlesize": 9,
        "legend.fontsize": 8,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "axes.linewidth": 0.7,
        "lines.linewidth": 1.1,
        "axes.grid": True,
        "grid.alpha": 0.25,
        "grid.linewidth": 0.5,
        "figure.dpi": 160,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.02,
        "pdf.fonttype": 42,
    }
)
C = {
    "RAW": "#8c8c8c",
    "WITHIN": "#1f77b4",
    "FULL": "#c1272d",
    "SINGLE": "#555555",
    "RQMC": "#2e7d32",
    "ref": "#111111",
}
NAME = {
    "RAW": "reflected",
    "WITHIN": "within-sign",
    "FULL": "sign-switched",
    "SINGLE": "unpaired",
    "RQMC": "RQMC",
}


def jload(p):
    return json.load(open(p))


# ---------------------------------------------------------------- figure 1
def fig_construction():
    """A real paired state: the interleaved-sign configuration after 10 steps."""
    from studies.study_round21_applicability import config
    from coupled_gradient_particles import advance_pair

    N, K, SEED = 12, 10, 2
    x0, m0, ul = config("clustered", N)
    captured = {}

    def capture(k, xA, mA, vA, xB, mB, vB):
        if k == K - 1:
            captured.update(xA=xA, mA=mA, xB=xB, mB=mB)

    advance_pair(
        (x0, m0, ul),
        0.1,
        0.005,
        K,
        np.random.default_rng(SEED),
        "FULL",
        lambda u: u,
        pre_diffusion=capture,
    )
    xA, mA, xB, mB = (captured[k] for k in ("xA", "mA", "xB", "mB"))
    assert np.all(np.diff(xA) >= 0) and np.all(np.diff(xB) >= 0)
    sA, sB = np.sign(mA), np.sign(mB)

    fig, axes = plt.subplots(1, 2, figsize=(6.6, 2.35))
    for ax, rule in zip(axes, ("rank", "within")):
        for y, xx, ss in ((1.0, xA, sA), (0.0, xB, sB)):
            for xi, si in zip(xx, ss):
                ax.plot(
                    [xi],
                    [y],
                    marker="o" if si > 0 else "s",
                    ms=5.4,
                    mfc="#e8e8e8" if si > 0 else "#333333",
                    mec="#111111",
                    mew=0.6,
                    linestyle="none",
                    zorder=3,
                )
        if rule == "rank":
            pairs = [(i, i, sA[i] * sB[i]) for i in range(len(xA))]
            ttl = "rank matching, multiplier $-\\,\\mathrm{sgn}(m_{A,i})\\mathrm{sgn}(m_{B,i})$"
        else:
            pairs = []
            for sgn in (1.0, -1.0):
                ia = np.flatnonzero(sA == sgn)
                ib = np.flatnonzero(sB == sgn)
                q = min(len(ia), len(ib))
                pairs += [(ia[k], ib[k], 1.0) for k in range(q)]
            ttl = "within-sign matching, multiplier $-1$"
        nsw = 0
        for i, j, mult in pairs:
            sync = mult < 0
            nsw += sync
            ax.plot(
                [xA[i], xB[j]],
                [1.0, 0.0],
                color="#c1272d" if sync else "#4d4d4d",
                ls=(0, (2.4, 1.4)) if sync else "-",
                lw=1.0,
                zorder=2,
                alpha=0.95,
            )
        ax.set_title(ttl, pad=5, fontsize=8.5)
        ax.set_ylim(-0.55, 1.55)
        ax.set_yticks([0.0, 1.0])
        ax.set_yticklabels(["replica $B$", "replica $A$"])
        ax.set_xlabel("position $x$")
        ax.set_xlim(min(xA.min(), xB.min()) - 0.04, max(xA.max(), xB.max()) + 0.04)
        ax.grid(axis="x", alpha=0.2)
        ax.grid(axis="y", alpha=0)
        ax.set_axisbelow(True)
        ax.text(
            0.985,
            0.06,
            f"{nsw} of {len(pairs)} synchronised",
            transform=ax.transAxes,
            ha="right",
            va="bottom",
            fontsize=7.5,
            color="#666666",
        )
    h = [
        Line2D(
            [],
            [],
            marker="o",
            ls="none",
            mfc="#e8e8e8",
            mec="#111",
            ms=5.4,
            label="$m_i>0$",
        ),
        Line2D(
            [],
            [],
            marker="s",
            ls="none",
            mfc="#333333",
            mec="#111",
            ms=5.4,
            label="$m_i<0$",
        ),
        Line2D([], [], color="#4d4d4d", lw=1.0, label="reflected: $Z_B=-Z_A$"),
        Line2D(
            [],
            [],
            color="#c1272d",
            lw=1.0,
            ls=(0, (2.4, 1.4)),
            label="synchronised: $Z_B=+Z_A$",
        ),
    ]
    fig.legend(
        handles=h,
        ncol=4,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.10),
        frameon=False,
        columnspacing=1.5,
        handletextpad=0.6,
    )
    fig.tight_layout()
    fig.savefig(FIG / "fig1_construction.pdf")
    plt.close(fig)
    np.savez(
        HERE / "fig1_state.npz",
        xA=xA,
        mA=mA,
        xB=xB,
        mB=mB,
        config=np.array(["clustered"]),
        N=N,
        K=K,
        seed=SEED,
    )
    print("fig1_construction.pdf")


# ---------------------------------------------------------------- figure 2
def fig_fields():
    z = np.load(REVIEW / "replayed_fields.npz")
    x = z["x"]
    ref = z["reference"]
    fig, axes = plt.subplots(
        1, 3, figsize=(6.8, 2.25), gridspec_kw={"width_ratios": [1, 1, 1.22]}
    )
    r = 3
    lim = 0
    for a in ("RAW", "FULL"):
        lim = max(
            lim, np.abs(z[f"{a}_A"][r] - ref).max(), np.abs(z[f"{a}_B"][r] - ref).max()
        )
    lim *= 1.08
    for ax, a in zip(axes[:2], ("RAW", "FULL")):
        ax.axhline(0.0, color="#111111", lw=0.6, ls=":")
        ax.plot(x, z[f"{a}_A"][r] - ref, color=C[a], lw=0.7, alpha=0.42)
        ax.plot(x, z[f"{a}_B"][r] - ref, color=C[a], lw=0.7, alpha=0.42)
        ax.plot(x, 0.5 * (z[f"{a}_A"][r] + z[f"{a}_B"][r]) - ref, color=C[a], lw=1.3)
        ax.set_xlim(-3, 3)
        ax.set_ylim(-lim, lim)
        ax.set_xlabel("$x$")
        ax.set_title(f"{NAME[a]} pairing", fontsize=8.5)
    axes[0].set_ylabel("$u(x,T)-u_{\\mathrm{ref}}(x,T)$")
    axes[1].set_yticklabels([])
    axes[0].text(
        0.03,
        0.04,
        "faint: the two replicas\nbold: their mean",
        transform=axes[0].transAxes,
        fontsize=7.2,
        color="#666666",
        va="bottom",
    )

    ax = axes[2]
    v = {a: 0.5 * (z[f"{a}_A"] + z[f"{a}_B"]) for a in ("RAW", "WITHIN", "FULL")}
    var = {a: v[a].var(0, ddof=1) for a in v}
    g = np.abs(np.gradient(ref, x[1] - x[0]))
    ax2 = ax.twinx()
    ax2.fill_between(x, 0, g / g.max(), color="#9ecae1", alpha=0.45, lw=0, zorder=0)
    ax2.set_ylim(0, 2.6)
    ax2.set_yticks([])
    ax2.grid(False)

    def smooth(y, w=13):
        k = np.ones(w) / w
        return np.convolve(np.pad(y, w // 2, mode="edge"), k, mode="valid")[: len(y)]

    for num, den, col, lab in (
        ("FULL", "RAW", C["FULL"], "vs reflected"),
        ("FULL", "WITHIN", C["WITHIN"], "vs within-sign"),
    ):
        rr = np.divide(
            var[num],
            var[den],
            out=np.full_like(var[num], np.nan),
            where=var[den] > 1e-10 * var[den].max(),
        )
        ax.plot(x, rr, color=col, lw=0.5, alpha=0.3, zorder=2)
        ax.plot(x, smooth(rr), color=col, lw=1.4, zorder=3, label=lab)
    ax.axhline(1.0, color="#111111", lw=0.6, ls=":")
    ax.set_xlim(-3, 3)
    ax.set_ylim(0, 1.45)
    ax.set_zorder(ax2.get_zorder() + 1)
    ax.patch.set_visible(False)
    ax.set_xlabel("$x$")
    ax.set_ylabel("pointwise variance ratio")
    ax.set_title("where the reduction sits", fontsize=8.5)
    ax.legend(frameon=False, loc="lower left", fontsize=7.2)
    fig.tight_layout()
    fig.savefig(FIG / "fig2_fields.pdf")
    plt.close(fig)
    print("fig2_fields.pdf")


# ---------------------------------------------------------------- figure 3
def fig_profiles():
    mech = jload(ARCH / "round23_mechanism_2026_09_10/mechanism.json")["rows"]
    sep = jload(ARCH / "round24_separation_2026_09_10/separation.json")["rows"]
    profiles = ["P1 single bump", "P2 two-pulse", "P3 oscillatory"]
    lab = {
        "P1 single bump": "single bump (2 sign regions)",
        "P2 two-pulse": "two-pulse (3)",
        "P3 oscillatory": "oscillatory (13)",
    }
    col = {
        "P1 single bump": "#4d4d4d",
        "P2 two-pulse": "#1f77b4",
        "P3 oscillatory": "#c1272d",
    }
    mk = {"P1 single bump": "o", "P2 two-pulse": "s", "P3 oscillatory": "^"}
    T = [0.25, 1.0, 2.0]
    fig, axes = plt.subplots(1, 2, figsize=(6.6, 2.7), sharex=True)

    ax = axes[0]
    for p in profiles:
        rs = [r for r in mech if r["profile"] == p]
        y = [r["full_over_within"] for r in rs]
        lo = [r["full_over_within"] - r["ci"][0] for r in rs]
        hi = [r["ci"][1] - r["full_over_within"] for r in rs]
        ax.errorbar(
            T,
            y,
            yerr=[lo, hi],
            color=col[p],
            marker=mk[p],
            ms=4.2,
            lw=1.1,
            capsize=2.5,
            label=lab[p],
        )
    ax.axhline(1.0, color="#111111", lw=0.7, ls=":")
    ax.set_xlabel("observation time $T$")
    ax.set_ylabel("variance ratio")
    ax.set_title("integrated variance ratio", fontsize=8.5)
    ax.set_xticks(T)
    ax.set_ylim(0.5, 1.08)

    ax = axes[1]
    for p in profiles:
        rs = [r for r in sep if r["kind"] == "matched_state" and r["profile"] == p]
        y = [r["ratio"] for r in rs]
        e = [2 * r["se"] for r in rs]
        ax.errorbar(
            T, y, yerr=e, color=col[p], marker=mk[p], ms=4.2, lw=1.1, capsize=2.5
        )
    ax.axhline(1.0, color="#111111", lw=0.7, ls=":")
    ax.set_xlabel("observation time $T$")
    ax.set_ylabel("matched-separation ratio")
    ax.set_title("matched-pair separation ratio", fontsize=8.5)
    ax.set_xticks(T)
    ax.set_ylim(0.5, 1.08)
    ax.text(
        0.98,
        0.05,
        r"$\leq 1$ by construction",
        transform=ax.transAxes,
        ha="right",
        va="bottom",
        fontsize=7.5,
        color="#666666",
    )
    h = [
        Line2D([], [], color=col[p], marker=mk[p], ms=4.2, lw=1.1, label=lab[p])
        for p in profiles
    ]
    fig.tight_layout()
    fig.legend(
        handles=h,
        ncol=3,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.10),
        frameon=False,
        columnspacing=1.8,
    )
    fig.savefig(FIG / "fig3_profiles.pdf")
    plt.close(fig)
    print("fig3_profiles.pdf")


# ---------------------------------------------------------------- figure 4
def fig_bias():  # Figure 5 in the manuscript
    jc = jload(ARCH / "round07_joint_cell_2026_09_09/joint_cell.json")["rows"]
    fig, ax = plt.subplots(figsize=(3.5, 2.6))
    styles = ["-", "--", ":"]
    for row, ls in zip(jc, styles):
        b2, Vf, Vr = row["b2_full"], row["V_full"], row["V_raw"]
        Cf, Cr = row["cost_full"], row["cost_raw"]
        W = np.geomspace(max(Cf, Cr), 4000 * Cf, 500)
        ratio = (b2 + Vf * Cf / W) / (b2 + Vr * Cr / W)
        ax.plot(
            W,
            ratio,
            ls=ls,
            color="#c1272d",
            lw=1.2,
            label=rf"$N={row['N']}$, $h={row['h']}$",
        )
        Bs = row["Bstar_full"]
        ax.plot(
            [Bs * Cf],
            [(b2 + Vf / Bs) / (b2 + Vr * Cr / (Bs * Cf))],
            marker="o",
            ms=4.5,
            mfc="white",
            mec="#c1272d",
            mew=1.1,
            zorder=4,
        )
    ax.set_xscale("log")
    ax.set_xlabel("common work budget (s)")
    ax.set_ylabel("mean squared error ratio")
    ax.set_title("sign-switched / reflected at fixed $N,h$", fontsize=8.5)
    ax.axhline(1.0, color="#111111", lw=0.7, ls=":")
    ax.set_ylim(0, 1.08)
    ax.legend(frameon=False, loc="lower right", fontsize=7.5)
    ax.text(
        0.03,
        0.06,
        r"$\circ$  $W=C_{\rm switch}V_{\rm switch}/b^{2}$",
        transform=ax.transAxes,
        fontsize=7.5,
        color="#666666",
        va="bottom",
    )
    fig.tight_layout()
    fig.savefig(FIG / "fig5_bias.pdf")
    plt.close(fig)
    print("fig5_bias.pdf")


# ---------------------------------------------------------------- figure 5
def fig_heldout():  # Figure 4 in the manuscript
    A = jload(HERE / "numbers.json")["heldout_A"]
    B = jload(HERE / "numbers.json")["heldout_B"]
    fig, axes = plt.subplots(1, 2, figsize=(6.6, 2.5))

    ax = axes[0]
    order = ["SINGLE", "RQMC", "RAW", "FULL"]
    w = [A["arms"][a]["work_s"] for a in order]
    ax.barh(range(len(order)), w, color=[C[a] for a in order], height=0.6)
    for i, a in enumerate(order):
        ax.text(
            w[i] + 0.12,
            i,
            f"{w[i]:.2f} s  ({A['arms'][a]['trajectories']} traj.)",
            va="center",
            fontsize=7.5,
        )
    ax.set_yticks(range(len(order)))
    ax.set_yticklabels([NAME[a] for a in order])
    ax.set_xlim(0, 9.2)
    ax.set_xlabel("measured work (s)")
    ax.set_title(r"experiment A: target $7\times10^{-6}$, $N=8192$", fontsize=8.5)
    ax.grid(axis="y", alpha=0)

    ax = axes[1]
    order = ["RAW", "WITHIN", "FULL"]
    w = [B["arms"][a]["work_interleaved_s"] for a in order]
    ax.barh(range(len(order)), w, color=[C[a] for a in order], height=0.6)
    for i, a in enumerate(order):
        ax.text(
            w[i] + 0.012,
            i,
            f"{w[i]:.3f} s  ({B['arms'][a]['trajectories']} traj.)",
            va="center",
            fontsize=7.5,
        )
    ax.set_yticks(range(len(order)))
    ax.set_yticklabels([NAME[a] for a in order])
    ax.set_xlim(0, 0.85)
    ax.set_xlabel("measured work (s)")
    ax.set_title(r"experiment B: target $2.5\times10^{-5}$, $N=2048$", fontsize=8.5)
    ax.grid(axis="y", alpha=0)
    fig.tight_layout()
    fig.savefig(FIG / "fig4_heldout.pdf")
    plt.close(fig)
    print("fig4_heldout.pdf")


if __name__ == "__main__":
    FIG.mkdir(exist_ok=True)
    fig_construction()
    fig_fields()
    fig_profiles()
    fig_bias()
    fig_heldout()
